name: chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.5
  flutterfire_cli: ^0.2.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flutter:
    sdk: flutter
  rive: ^0.10.3
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/GChatLogo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Gruppo
      fonts:
        - asset: assets/fonts/Gruppo-Regular.ttf
