// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO33ZtDhHXDqcrwGGtu2LbRDBLh34joSM',
    appId: '1:158267982169:web:34389d515b5d695fefcc48',
    messagingSenderId: '158267982169',
    projectId: 'chatapp-ayisha',
    authDomain: 'chatapp-ayisha.firebaseapp.com',
    storageBucket: 'chatapp-ayisha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBNaeuVIWKLddffat2tVu2KB7chsI4jdE',
    appId: '1:158267982169:android:0cdb4cb9cd1da0c3efcc48',
    messagingSenderId: '158267982169',
    projectId: 'chatapp-ayisha',
    storageBucket: 'chatapp-ayisha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA87H_aJjC_-UvPdsdJzFBkor15GnYFL3o',
    appId: '1:158267982169:ios:d9a37e2989ccd581efcc48',
    messagingSenderId: '158267982169',
    projectId: 'chatapp-ayisha',
    storageBucket: 'chatapp-ayisha.appspot.com',
    androidClientId: '158267982169-r0425atnvatehclrfi1m09s24mfjm5s3.apps.googleusercontent.com',
    iosClientId: '158267982169-5sboj9ap7t9tftujpr41t74qfb0m92km.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA87H_aJjC_-UvPdsdJzFBkor15GnYFL3o',
    appId: '1:158267982169:ios:d9a37e2989ccd581efcc48',
    messagingSenderId: '158267982169',
    projectId: 'chatapp-ayisha',
    storageBucket: 'chatapp-ayisha.appspot.com',
    androidClientId: '158267982169-r0425atnvatehclrfi1m09s24mfjm5s3.apps.googleusercontent.com',
    iosClientId: '158267982169-5sboj9ap7t9tftujpr41t74qfb0m92km.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
